Fix signal delivery problem.

diff --git a/cifs-debug.ds.yaml b/cifs-debug.ds.yaml
--- a/cifs-debug.ds.yaml
+++ b/cifs-debug.ds.yaml
@@ -24,12 +24,12 @@ spec:
                   disk_usage=$(df -h / | awk '{print $5}' | tail -n 1)
                   disk_usage_percent=${disk_usage%%%}
                   if [[ $disk_usage_percent > 50 ]]; then exit 199; fi
-            initialDelaySeconds: 5 
+            initialDelaySeconds: 5
             periodSeconds: 10
           lifecycle:
             preStop:
               exec:
-                command: ["/bin/sh","-c","while killall cifs_credit_diag.sh; do sleep 1; done"]
+                command: ["/bin/sh","-c","while pkill -SIGURG -f bash; do sleep 1; done"]
           command:
             - nsenter
             - --target
@@ -43,25 +43,24 @@ spec:
             - -c
             - |
                 #!/bin/bash
-                if ! command -v trace-cmd &> /dev/null
-                  then
-                  # If trace-cmd is not installed, attempt to install it
-                  echo "trace-cmd is not installed. Attempting to install..."
-
+                if ! command -v trace-cmd &> /dev/null;
+                then
+                 # If trace-cmd is not installed, attempt to install it
+                    echo "trace-cmd is not installed. Attempting to install..."
                  # Install trace-cmd using apt-get
-                 DEBIAN_FRONTEND=noninteractive apt-get install -y trace-cmd
+                    DEBIAN_FRONTEND=noninteractive apt-get install -y trace-cmd
 
                  # Check if installation was successful
-                 if ! command -v trace-cmd &> /dev/null
-                   then
-                   echo "Error: Failed to install trace-cmd." >&2
-                   exit 201
-                   else
-                   echo "trace-cmd is now installed."
-                 fi
-                 else
-                 # If trace-cmd is already installed, print a message indicating that it's installed
-                 echo "trace-cmd is already installed."
+                    if ! command -v trace-cmd &> /dev/null
+                    then
+                        echo "Error: Failed to install trace-cmd." >&2
+                        exit 201
+                    else
+                        echo "trace-cmd is now installed."
+                    fi
+                else
+                # If trace-cmd is already installed, print a message indicating that it's installed
+                    echo "trace-cmd is already installed."
                 fi
                 ## ================ USER PARAMS ====================== ##
                 DETECTION_INTERVAL_SEC=10   # dump "frequent" statistics once in this interval
@@ -84,15 +83,13 @@ spec:
                 CRITICAL_TRIGGER_LOG="$LOGDIR/critical_triggers"
                 DEBUGDATA_TMP="$LOGDIR/cifs_debug_data.tmp"
                 DEBUGDATA_OUT="$LOGDIR/cifs_debug_data"
-                CIFS_TRACE_DAT="trace.dat"
+                CIFS_TRACE_DAT="$LOGDIR/trace.dat"
                 CIFS_TRACE_OUT="$LOGDIR/cifs_trace"
                 STATS_OUT="$LOGDIR/cifs_stats_out"
                 DMESG_OUT="$LOGDIR/cifs_dmesg"
                 CREDIT_HIST="$LOGDIR/cifs_credit_history"
                 UNIQUE_HOSTNAMES="$LOGDIR/unique_sessions_hostnames"
                 MY_PIDFILE="/tmp/cifs_credits_diag.pid"
-
-                TRACE_CMD_INVOCATION="nohup trace-cmd record -e cifs -m $TRACE_CMD_BUFSZ_BYTES"
                 ##
 
                 INITIAL_UPTIME=0
@@ -116,14 +113,15 @@ spec:
                     tarball_name="$(hostname)_${datestr}_UTC_logs_${LOG_ROTATE_COUNT}.tgz"
                     temp_logdir="${LOGDIR}_${datestr}"
                     cp -r $LOGDIR "$temp_logdir"
-                    tar czf $tarball_name $temp_logdir
+                    tar czf "/tmp/$tarball_name" $temp_logdir
                     rm -fR $temp_logdir
                     LOG_ROTATE_COUNT=$((LOG_ROTATE_COUNT + 1))
 
-                    #Get rid of the oldest N logs?
                     rm -fR $LOGDIR;
                     mkdir $LOGDIR;
-                    find $LOGDIR -type f -mtime +3 -exec rm -f {} \;
+
+                    #Get rid of tarballs that are older than 3 days
+                    find /tmp -type f -name "$(hostname)*.tgz" -mtime +3 -exec rm -f {} \;
                 }
 
                 setup_logdir() {
@@ -150,7 +148,8 @@ spec:
                     echo 'file fs/cifs* +p' > /sys/kernel/debug/dynamic_debug/control
                     echo 7 > /proc/fs/cifs/cifsFYI
 
-                    $TRACE_CMD_INVOCATION 0<&- > /dev/null 2>&1 &
+                    trace-cmd reset
+                    trace-cmd start -e cifs
                 }
 
                 check_diagcmds_present() {
@@ -162,50 +161,49 @@ spec:
                 }
 
                 check_space_consumption() {
-                         # Set the number of measurements to keep for calculating growth rate
-                       num_measurements=10
-                       check_space_consumption() {
-                       # Get the initial size of the root filesystem
-                       initial_size=$(df -h / | awk 'NR==2{print $3}')
+                    # Set the number of measurements to keep for calculating growth rate
+                    num_measurements=10
+                    # Get the initial size of the root filesystem
+                    initial_size=$(df -h / | awk 'NR==2{print $3}')
 
-                       # Initialize an array to hold the previous measurements
-                       measurements=($initial_size)
+                    # Initialize an array to hold the previous measurements
+                    measurements=($initial_size)
 
-                       # Loop until the root filesystem utilization is at or above 50%
-                       #while true; do
-                       # Wait for the specified interval
-                       #   sleep $interval
+                    # Loop until the root filesystem utilization is at or above 50%
+                    # while true; do
+                    # Wait for the specified interval
+                    #   sleep $interval
 
-                       # Get the current size of the root filesystem
-                       current_size=$(df -h / | awk 'NR==2{print $3}')
+                    # Get the current size of the root filesystem
+                    current_size=$(df -h / | awk 'NR==2{print $3}')
 
-                       # Calculate the growth rate over the last 10 minutes
-                       num_measurements=${#measurements[@]}
-                       if (( num_measurements < 2 )); then
+                    # Calculate the growth rate over the last 10 minutes
+                    num_measurements=${#measurements[@]}
+                    if (( num_measurements < 2 )); then
                           growth_rate="N/A"
-                       else
+                    else
                           growth=$((${measurements[$num_measurements-1]} - ${measurements[$num_measurements-2]}))
                           growth_rate=$(echo "scale=2; $growth/$interval" | bc)
                           growth_rate="$growth_rate MB/s"
-                       fi
+                    fi
 
-                       # Write the current size and growth rate to a file
-                       echo "$(date '+%Y-%m-%d %H:%M:%S'),$current_size,$growth_rate" >> disk_usage.csv
+                    # Write the current size and growth rate to a file
+                    echo "$(date '+%Y-%m-%d %H:%M:%S'),$current_size,$growth_rate" >> disk_usage.csv
 
-                       # Check if the root filesystem utilization is above 50%
-                       usage=$(df -h / | awk 'NR==2{print $5}' | sed 's/%//')
-                       if (( usage >= 50 )); then
+                    # Check if the root filesystem utilization is above 50%
+                    usage=$(df -h / | awk 'NR==2{print $5}' | sed 's/%//')
+                    if (( usage >= 50 )); then
                           echo "Error: Root filesystem utilization is above 50%. Stopping script."
                           exit 198
-                       fi
+                    fi
 
-                       # Add the current measurement to the array
-                       measurements+=($current_size)
-                       # Remove the oldest measurement if the array has reached its maximum size
-                       if (( ${#measurements[@]} > $num_measurements )); then
+                    # Add the current measurement to the array
+                    measurements+=($current_size)
+                    # Remove the oldest measurement if the array has reached its maximum size
+                    if (( ${#measurements[@]} > $num_measurements )); then
                           measurements=("${measurements[@]:1}")
-                       fi
-                       #done
+                    fi
+                    #done
                 }
 
                 collect_initial_info() {
@@ -232,14 +230,15 @@ spec:
                     setup_logdir;
                     check_diagcmds_present |tee $ERR_LOG
                     setup_debug;
-                        collect_initial_info > $INITIAL_INFO ;
+                    collect_initial_info > $INITIAL_INFO ;
 
                     trap stop_collection_and_exit SIGINT;
+                    trap stop_collection_and_exit SIGURG;
 
-                    echo $! > $MY_PIDFILE
+                    echo $$ > $MY_PIDFILE
                     echo "-----------------------------------------------------------------------------"
                     echo "Collecting CIFS credit and related stats ($(date -u +'%Y %b %d %H:%M:%S UTC'))"
-                    echo "To stop log collection, please hit Ctrl-C, or run \"kill -9 $!\" as root"
+                    echo "To stop log collection, please hit Ctrl-C, or run \"kill -9 $$\" as root"
                     echo "-----------------------------------------------------------------------------"
                 }
 
@@ -299,21 +298,21 @@ spec:
                         collect_infrequent_stats
                     fi
 
-                    log_credit_score_trigger=$((wcnt % CREDIT_LOG_INTERVAL_MULT))
-                    if (( $log_credit_score_trigger == 0 ))
-                    then
-                        # extract session id, mountpoint, credit score, and inflight requests.
-                        # log these to syslog.
-                        egrep -A3 'ConnectionId' /proc/fs/cifs/DebugData    |
-                            tr -d '\n'                                      |
-                            sed 's/--/\n/g' > $DEBUGDATA_TMP
-                        echo >> $DEBUGDATA_TMP
+                    #log_credit_score_trigger=$((wcnt % CREDIT_LOG_INTERVAL_MULT))
+                    #if (( $log_credit_score_trigger == 0 ))
+                    #then
+                    #    # extract session id, mountpoint, credit score, and inflight requests.
+                    #    # log these to syslog.
+                    #    egrep -A3 'ConnectionId' /proc/fs/cifs/DebugData    |
+                    #        tr -d '\n'                                      |
+                    #        sed 's/--/\n/g' > $DEBUGDATA_TMP
+                    #    echo >> $DEBUGDATA_TMP
 
-                        while read cr_log_line; do
-                            logger -p local0.warning "CIFS_CREDIT_LOG: $datestr $cr_log_line"
-                        done<$DEBUGDATA_TMP
-                    fi
-                    rm -f $DEBUGDATA_TMP
+                    #    while read cr_log_line; do
+                    #        logger -p local0.warning "CIFS_CREDIT_LOG: $datestr $cr_log_line"
+                    #    done<$DEBUGDATA_TMP
+                    #fi
+                    #rm -f $DEBUGDATA_TMP
 
                 }
 
@@ -372,7 +371,7 @@ spec:
                             # rotate logs, and _continue_ until we hit the termination condition.
                             #
                             logs_need_rotation=1
-                            logger -p local0.warning "CIFS_CREDIT_ALERT: low credit on $hostsession"
+                            #logger -p local0.warning "CIFS_CREDIT_ALERT: low credit on $hostsession"
                         fi
 
                         #
@@ -397,9 +396,9 @@ spec:
                             logs_need_rotation=1
 
                             # We keep running even if we hit the termination condition
-                            #echo "--> Stopping log collection"
-                            #teardown
-                            #exit 1
+                            echo "--> Stopping log collection"
+                            teardown
+                            exit 1
                         fi
                     done<$UNIQUE_HOSTNAMES
 
@@ -430,18 +429,10 @@ spec:
                 }
 
                 kill_trace_cmd_gen_report() {
-                    local retry=0
-                        local trace_cmd_pid=$(pgrep trace-cmd | head -1)
-
-                    kill -INT $trace_cmd_pid
-                    while [ $? == 0 ] && [ $retry -lt 10 ]
-                    do
-                           retry=$(( retry + 1 ))
-                       sleep 1
-                           ps -p "$trace_cmd_pid" > /dev/null
-                    done
-
-                    trace-cmd report > $CIFS_TRACE_OUT
+                    date >> "$LOGDIR/stop_attempts"
+                    trace-cmd stop
+                    trace-cmd extract -o $CIFS_TRACE_DAT
+                    trace-cmd report -i $CIFS_TRACE_DAT >> $CIFS_TRACE_OUT
                 }
 
                 teardown_debug() {
@@ -474,10 +465,10 @@ spec:
 
                     cur_tarball_prefix="$(hostname)_$(date -u +'%Y%b%d-%H-%M-%S')_UTC_logs"
                     tarball_name="${cur_tarball_prefix}_${LOG_ROTATE_COUNT}.tgz"
-                    tar czf $tarball_name $LOGDIR
+                    tar czf "/tmp/$tarball_name" $LOGDIR
 
                     composite_tarball_name="COMPOSITE_${cur_tarball_prefix}.tgz"
-                    tar czf $composite_tarball_name ./$(hostname)_*
+                    tar czf "/tmp/$composite_tarball_name" /tmp/*.tgz "$LOGDIR"
                     echo ""
                     echo "==> Created composite tarball $composite_tarball_name"
                     echo "Please send a copy of this tarball to Microsoft support for further analysis"
